main: net.cupofcode.instruments.Instruments
name: Instruments
version: '1.4'
description: Adds various net.cupofcode.instruments to your server
author: CupOfCode
api-version: 1.14
depend: [ProtocolLib]
commands:
  instruments:
    description: all commands related to Instruments