main: instruments.Instruments
name: Instruments
version: '1.1'
description: Adds various instruments to your server
author: CupOfCode
api-version: 1.14
depend: [ProtocolLib]
commands:
  instruments:
    description: all commands related to Instruments